### ISSUE TITLE
Backdrop Error

### ISSUE THREAD

**Issue by Meebsy** [nihilistzsche/RematchElvUISkin#1]
**Description**
Some kind of backdrop skinning issue, not complete sure how it effects the skin.

**NihilistzscheUI Version**

**ElvUI Version**

13.02

**Steps to Reproduce**

1. Step 1 - Log in
2. Step 2 - ...
3. Step 3 - ...
4. Step 4 - Profit

**Expected Behavior**

**Actual Behavior**

**Mention what addons you are using.**

**Additional Information**

**Error Log**

```
 ...terface/AddOns/RematchElvUISkin/RematchElvUISkin.lua:345: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface/AddOns/RematchElvUISkin/RematchElvUISkin.lua"]:345: in function `func'
[string "@Interface/AddOns/RematchElvUISkin/RematchElvUISkin.lua"]:653: in function <...terface/AddOns/RematchElvUISkin/RematchElvUISkin.lua:649>
```

**Comment by nihilistzsche** [comment]
The current version on github fixes this, my release script isnt working at the moment but I will upload it soon.
